import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cardápio Digital da Bolu',
  description: 'Generated by create next app',
};

export default function DashboardLayouts({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      <Header />
      <main className={inter.className}>{children}</main>
    </div>
  );
}
